services:
  - type: web
    name: pitchai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python startup.py && gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health
    autoDeploy: true 